name 'proteon-liferay'
version '0.1.2'

author 'Proteon'
license 'Apache License, Version 2.0'
project_page 'https://github.com/Proteon/puppet-liferay'
source 'http://github.com/Proteon/puppet-liferay.git'
summary 'Puppet code for deploying and configuring Liferay in Tomcat'
description 'Puppet code for deploying and configuring Liferay in Tomcat'
dependency 'ripienaar/concat', '>=0.2.0'
