name 'proteon-liferay'
version '0.1.1'

author 'Proteon'
license 'Apache License, Version 2.0'
project_page 'https://github.com/Proteon/puppet-liferay'
source 'git@github.com:Proteon/puppet-liferay.git'
summary 'Puppet code for deploying and configuring Liferay in Tomcat'
description 'Puppet code for deploying and configuring Liferay in Tomcat'
dependency 'proteon/tomcat', '>=0.1.5'
dependency 'ripienaar/concat', '>=0.2.0'
dependency 'proteon/maven', '>=1.0.1'
dependency 'proteon/java', '>=0.1.4'
